server.port: 8080

spring:
  application:
    name: consumer-ws

ws:
  version: '@project.version@'

---

spring.config.activate.on-profile: local
server:
  port: 8081

spring:
  data:
    mongodb:
      database: publisher-ws
      uri: mongodb://localhost:27017
  kafka:
    bootstrap-servers: localhost:29092
    client-id: consumer-ws-client
    consumer.group-id: consumer-ws-group
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-interval: 10000
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
    producer:
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false


logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
